USE minecraft_autologin;

ALTER TABLE cards ADD COLUMN IF NOT EXISTS banned BOOLEAN DEFAULT FALSE;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS last_ip VARCHAR(50);
ALTER TABLE cards ADD COLUMN IF NOT EXISTS success_count INT DEFAULT 0;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS fail_count INT DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_banned ON cards(banned);
